// HAREMOS UN MODULO CON LAS 4 OPERACIONES MATEMÁTICAS BÁSICAS

// EL NAME PUESTO EN PACKAGE.JSON SERA EL NOMBRE CON EL QUE SE PUBLICA

// PASOS PARA PUBLICAR EL PAQUETE:
// LOGUEARSE DESDE LA CONSOLA A NPM
// npm login

// A PARTIR DE 2026,SE REQUIERE GENERAR UN TOKEN PARA PUBLICAR
// EN EL PANEL DERECHO DE NPM UNA VEZ LOGUEADO, IR AL AVATAR
// Y DAR CLICK EN ACCESS TOKENS
// UNA VEZ ALLI, CLICK EN "GENERATE TOKEN" Y COMPLETAR LOS CAMPOS
// TILDAR LA OPCION "BYPASS TWO FACTOR AUTHENTICATION"
// PONER PERMISOS EN EL DESPLEGABLE DE "PACKAGES AND SCOPES"

// LUEGO, SETEAR UNA CONFIGURACION EN LA CLI PASANDO EL TOKEN
// npm set //registry.npmjs.org/:_authToken=<TOKEN>

// AHORA SI, PARA PUBLICARLO
// npm publish --access public

// PARA INSTALARLO EN OTRO PROYECTO HACER:
// npm install <nombre del paquete>

// RECUERDEN QUE LA PROPIEDAD "MAIN" DEL PACKAGE.JSON INDICA EL ARCHIVO DE ENTRADA
// DEL PAQUETE, ASI QUE LAS FUNCIONALIDADES QUE DESARROLLAMOS DEBEN ESTAR
// EXPORTADAS DESDE ESE ARCHIVO